[build]
  base    = "docs"
  publish = "docs/build"
  command = "node index.js"

[context.production.environment]
  YARN_VERSION = "1.3.2"
  NODE_ENV = "production"
  ROOT_PATH = "/wordpress/"

[context.deploy-preview.environment]
  YARN_VERSION = "1.3.2"
  NODE_ENV = "production"
  ROOT_PATH = "/wordpress/"

[context.branch-deploy.environment]
  YARN_VERSION = "1.3.2"
  NODE_ENV = "production"
  ROOT_PATH = "/wordpress/"
  